# fly.toml app configuration file generated for flask-es-test on 2023-06-21T23:25:33+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "flask-es-test"
primary_region = "sin"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"
  MYSQL_DATABASE = "es_db"
  MYSQL_USER = "non_root_user"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
